# Generated by Django 3.0.6 on 2020-05-05 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100)),
                ('call_name', models.CharField(max_length=255)),
                ('call_start_time', models.DateTimeField(auto_now=True)),
                ('call_end_time', models.DateTimeField(auto_now=True)),
                ('call_text_url', models.CharField(max_length=25)),
                ('call_video_url', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CallParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100)),
                ('user_sid', models.CharField(max_length=25)),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Calls')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
