# Generated by Django 3.0.6 on 2020-05-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
